### ISSUE TITLE
Plotting spatial loadings is broken for PCR

### ISSUE THREAD

**Issue by aaron-kaplan** [iri-pycpt/pycpt#22]
Reported by Bernard from AGRHYMET. There are no pys when using PCR, but the code for plotting spatial loadings assumes that there are.

**Comment by awrobertson** [comment]
I have a proposed fix tested and ready for PR - once I solve authentication problem and am able to push it to GitHub

**Comment by aaron-kaplan** [comment]
Fixed in https://github.com/iri-pycpt/pycpt/commit/74ff291931d990d2b5f7aebbe9f14d42db86178f
