### ISSUE TITLE
Implement skill masking

### ISSUE THREAD

**Issue by awrobertson** [iri-pycpt/pycpt#63]
I will add to cca.py etc    
if skillmask:	
        cpt.write(5372)
        ...

What does CPT expect after that. Should a real value (eg 0.) then be passed?

However, can skill masking be applied when using cross-validated hindcasts, or only when using the retroactive option? PyCPT seasonal does not use the latter, so skill masking might not be possible. 

CPT help says:
https://cpthelp.iri.columbia.edu/Options_Masking.html

**Skill-masking applies only when calculating retroactive forecasts** and when running [Tools ~ Forecast ](https://cpthelp.iri.columbia.edu/Tools_Forecast.html). If the skill is less than the threshold indicated by "skill mask" then climatological forecasts will be issued. The skill can be measured using:
Pearson's correlation
Spearman's correlation
Kendall's tau
Kendall's tau-c
The skill is calculated using either the
cross-validated hindcasts, or
retroactive hindcasts, or
fitted values
depending upon how the forecast error variance (as set in [Options ~ Forecast ](https://cpthelp.iri.columbia.edu/Options_Forecast.html)) is calculated. The skill masking can be reset after running [Actions ~ Calculate ](https://cpthelp.iri.columbia.edu/Actions_Calculate.html).

**Comment by awrobertson** [comment]
Added to pcr.py and cca.py

And

    if skillmask:	
        cpt.write(5372)
        cpt.write('Y')
        cpt.write(1)	# for Pearson
        cpt.write(skillmask_value)	

plus bookkeeping to configuration.py 

def check_cpt_args(args):
    args = copy.copy(args)
    keys = ['transform_predictand', 'tailoring', 'cca_modes', 'x_eof_modes', 'y_eof_modes', 'crossvalidation_window', 'synchronous_predictors', 'scree', **'drymask', 'drymask_value','skillmask','skillmask_value',**'validation'] # AWR 04/06/24

    keytypes = {'transform_predictand': str, 'tailoring': str, 'cca_modes': tuple, 'x_eof_modes': tuple, 'y_eof_modes': tuple, 'crossvalidation_window': int, 'synchronous_predictors': bool, **<img width="1887" alt="PyCPT Skill masking" src="https://github.com/iri-pycpt/pycpt/assets/21113530/318268bf-0776-4c7c-a3d5-c305efcf9d63">** 'scree': bool, 'validation': str}

**Comment by simon2212** [comment]
I made changes as per Aaron's suggestions, but don't know how to submit them. Please let me know how to submit.

**Comment by aaron-kaplan** [comment]
Sorry I haven't been in touch about this. I am preparing a new version of
pycpt with rather massive changes to support station data, and I have
addressed my suggestions on that branch
<https://github.com/iri-pycpt/pycpt/pull/68>, which I hope to release soon.

Answering the question more generally, the mechanism I prefer for
submitting proposed changes is the pull request
<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests>.
The next time you (or anyone else) want to submit changes, we can walk
through that process together.

**Comment by aaron-kaplan** [comment]
Addressed in 
https://github.com/iri-pycpt/pycpt/commit/1ed6dedb68ef68ff3b923dc655bb7ad3b5d30627 and https://github.com/iri-pycpt/pycpt/commit/74ff291931d990d2b5f7aebbe9f14d42db86178f ( 
(already merged) and in https://github.com/iri-pycpt/pycpt/pull/75
